<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.1" />
    <PackageReference Include="Npgsql" Version="8.0.3" />
  </ItemGroup>

  <ItemGroup>
  <ProjectReference Include="..\Cinema.Common\Cinema.Common.csproj" />
  <ProjectReference Include="..\Cinema.Model\Cinema.Model.csproj" />
    <ProjectReference Include="..\Cinema.Repository.Common\Cinema.Repository.Common.csproj" />
    <ProjectReference Include="..\Cinema.Service.Common\Cinema.Service.Common.csproj" />
    <ProjectReference Include="..\Cinema.Service\Cinema.Service.csproj" />
    <ProjectReference Include="..\DTO\DTO.csproj" />
  </ItemGroup>
	
</Project>
